#!/bin/sh

set -e

tag="$1"
if [ -z "$tag" ]; then
  echo "Usage: $0 v1.0.0"
  exit 1
fi

name="fcpscene-${tag}.tar.gz"
url="https://github.com/ericfortis/final-cut-pro-scene-detect/archive/refs/tags/${tag}.tar.gz"

echo "Downloading tarball…"
curl -sSL -o "$name" "$url"

echo "Calculating SHA256…"
sha=$(shasum -a 256 "$name" | awk '{print $1}')


echo "$url"
echo "$sha"